const DISCOGRAPHY = [
    {
        title: "Gehehsywef",
        artists: ["Clawrez"],
        album: "Gehehsywef",
        no: 1,
        releaseDate: Date.parse("2020-05-08"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "OBNOXIOUS",
        artists: ["Clawrez"],
        album: "HARDCLAW",
        no: 1,
        releaseDate: Date.parse("2020-09-03"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "YOU’RE SUPER COOL",
        artists: ["Clawrez"],
        album: "HARDCLAW",
        no: 2,
        releaseDate: Date.parse("2020-09-03"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "HELLOR",
        artists: ["Clawrez"],
        album: "HARDCLAW",
        no: 3,
        releaseDate: Date.parse("2020-09-03"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Race of The World",
        artists: ["Clawrez"],
        album: "Race of The World",
        no: 1,
        releaseDate: Date.parse("2020-09-23"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Heartbroken Cheerfulness",
        artists: ["Clawrez"],
        album: "Heartbroken Cheerfulness",
        no: 1,
        releaseDate: Date.parse("2020-10-02"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "I Need Da Funk (Speedcore Remix)",
        artists: ["Clawrez"],
        album: "I Need Da Funk (Speedcore Remix)",
        no: 1,
        releaseDate: Date.parse("2020-10-15"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "-1°K",
        artists: ["Clawrez"],
        album: "-1°K",
        no: 1,
        releaseDate: Date.parse("2020-10-17"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "HAPPY4U",
        artists: ["Clawrez"],
        album: "HAPPY4U",
        no: 1,
        releaseDate: Date.parse("2020-11-30"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "The Kelp Forest",
        artists: ["Clawrez"],
        album: "The Kelp Forest",
        no: 1,
        releaseDate: Date.parse("2020-12-06"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Play With Them As They Burn",
        artists: ["Clawrez"],
        album: "Play With Them As They Burn",
        no: 1,
        releaseDate: Date.parse("2020-12-13"),
        genre: "Extratone",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Lucky-Charmed House Music",
        artists: ["Clawrez"],
        album: "Lucky-Charmed House Music",
        no: 1,
        releaseDate: Date.parse("2021-01-13"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "VAS-CLXIII",
        artists: ["Clawrez"],
        album: "VAS-CLXIII",
        no: 1,
        releaseDate: Date.parse("2021-01-18"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Floccinaucinihilipilification",
        artists: ["Clawrez"],
        album: "Floccinaucinihilipilification",
        no: 1,
        releaseDate: Date.parse("2021-01-26"),
        genre: "Splittercore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Broken Mirror",
        artists: ["Clawrez"],
        album: "Broken Mirror",
        no: 1,
        releaseDate: Date.parse("2021-02-10"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "I hate melodies.",
        artists: ["Clawrez"],
        album: "I hate melodies.",
        no: 1,
        releaseDate: Date.parse("2021-02-15"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "FREAKIN’ FIELDZ",
        artists: ["Clawrez"],
        album: "FREAKIN’ FIELDZ",
        no: 1,
        releaseDate: Date.parse("2021-02-27"),
        genre: "Hardtek",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "怖いマニアナイト！！",
        artists: ["Clawrez"],
        album: "怖いマニアナイト！！",
        no: 1,
        releaseDate: Date.parse("2021-04-03"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Tool-Assisted Suicide",
        artists: ["Clawrez"],
        album: "Tool-Assisted Suicide",
        no: 1,
        releaseDate: Date.parse("2021-05-14"),
        genre: "Splittercore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "When I Fell",
        artists: ["Clawrez"],
        album: "When I Fell",
        no: 1,
        releaseDate: Date.parse("2021-05-21"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "L.oV€",
        artists: ["Clawrez"],
        album: "L.oV€",
        no: 1,
        releaseDate: Date.parse("2021-06-13"),
        genre: "Uptempo Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "THIS SONG IS NOT FROM A RHYTHM GAME",
        artists: ["Clawrez"],
        album: "THIS SONG IS NOT FROM A RHYTHM GAME",
        no: 1,
        releaseDate: Date.parse("2021-07-09"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Baddie",
        artists: ["Clawrez", "MC Spydr"],
        album: "DOS TERROR",
        no: 1,
        releaseDate: Date.parse("2021-07-17"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Obstacle Course",
        artists: ["Clawrez"],
        album: "DOS TERROR",
        no: 2,
        releaseDate: Date.parse("2021-07-17"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "JACKPOT LAUNCHER",
        artists: ["Clawrez"],
        album: "White Pink Plus",
        no: 3,
        releaseDate: Date.parse("2021-07-20"),
        genre: "Frenchcore",
        label: "Nikidronov Labo",
        image: "",
        audioFile: "",
    },
    {
        title: "Mystery Alchemy",
        artists: ["Clawrez"],
        album: "Mystery Alchemy",
        no: 1,
        releaseDate: Date.parse("2021-08-01"),
        genre: "Frenchcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "nebula #6FDEF2",
        artists: ["Clawrez"],
        album: "nebula #6FDEF2",
        no: 1,
        releaseDate: Date.parse("2021-08-03"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "LIFEBUOY TEMPOSPLITTER",
        artists: ["Clawrez"],
        album: "LIFEBUOY TEMPOSPLITTER",
        no: 1,
        releaseDate: Date.parse("2021-08-14"),
        genre: "Uptempo Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "e621 -YIFFCOREDELUXE-",
        artists: ["Clawrez"],
        album: "e621 -YIFFCOREDELUXE-",
        no: 1,
        releaseDate: Date.parse("2021-08-24"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Yura Yura Sweet Genocide (Clawrez Bootleg)",
        artists: ["Kobaryo", "t+pazolite", "Clawrez"],
        album: "Yura Yura Sweet Genocide (Clawrez Bootleg)",
        no: 1,
        releaseDate: Date.parse("2021-08-24"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Angry Snoozy Lullaby",
        artists: ["Clawrez"],
        album: "Angry Snoozy Lullaby",
        no: 1,
        releaseDate: Date.parse("2021-08-31"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Your screams will not be heard through the concrete walls.",
        artists: ["Clawrez"],
        album: "Your screams will not be heard through the concrete walls.",
        no: 1,
        releaseDate: Date.parse("2021-09-17"),
        genre: "Industrial Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "You Can’t Gabber Faster Than Me",
        artists: ["Clawrez"],
        album: "You Can’t Gabber Faster Than Me",
        no: 1,
        releaseDate: Date.parse("2021-09-27"),
        genre: "Gabber",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Grudge Greedy",
        artists: ["Clawrez"],
        album: "Grudge Greedy",
        no: 1,
        releaseDate: Date.parse("2021-09-28"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Monotonous",
        artists: ["Clawrez"],
        album: "Monotonous",
        no: 1,
        releaseDate: Date.parse("2021-11-09"),
        genre: "Hardtek",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Unnecessary Speedcore",
        artists: ["Clawrez"],
        album: "Unnecessary Speedcore",
        no: 1,
        releaseDate: Date.parse("2021-11-12"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Hellish Felony",
        artists: ["Clawrez"],
        album: "Hellish Felony",
        no: 1,
        releaseDate: Date.parse("2021-12-27"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "help",
        artists: ["Clawrez"],
        album: "help",
        no: 1,
        releaseDate: Date.parse("2022-03-01"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Climax Spectrum",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 1,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Frenchcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Ambicholia",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 2,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Speedcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Hellish Felony",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 3,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Speedcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "HARHARD",
        artists: ["Clawrez", "NiKU"],
        album: "Climax Spectrum",
        no: 4,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Swifter",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 5,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Hardtek",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "There Are Gay Furries On The Moon",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 6,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Galactic Dawn",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 7,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Speedcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Cup of Terror",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 8,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Terrorcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Dance With Me",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 9,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Play With Them As They Burn (PYROMANIACAL Remaster)",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 10,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Extratone",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "怖いマニアナイト！！ (TOTEMOKOWAI Remaster)",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 11,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Goodnight",
        artists: ["Clawrez"],
        album: "Climax Spectrum",
        no: 12,
        releaseDate: Date.parse("2022-03-11"),
        genre: "Piano",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "All Gabber'd Out",
        artists: ["Clawrez"],
        album: "All Gabber'd Out",
        no: 1,
        releaseDate: Date.parse("2022-04-18"),
        genre: "Gabber",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "WHAT WAS THAT?",
        artists: ["Clawrez"],
        album: "Mind Manipulation",
        no: 21,
        releaseDate: Date.parse("2022-05-03"),
        genre: "Terrorcore",
        label: "SKRD!!!",
        image: "",
        audioFile: "",
    },
    {
        title: "One One Zero (Clawrez Bootleg)",
        artists: ["nnn", "Clawrez"],
        album: "One One Zero (Clawrez Bootleg)",
        no: 1,
        releaseDate: Date.parse("2022-06-20"),
        genre: "Doomcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "i was hurting, but you were there for me (and 300 other reasons i love you)",
        artists: ["Clawrez"],
        album: "i was hurting, but you were there for me (and 300 other reasons i love you)",
        no: 7,
        releaseDate: Date.parse("2022-06-27"),
        genre: "Extratone",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "憂懼と愛の曲",
        artists: ["Clawrez"],
        album: "2000 OVER!!",
        no: 1,
        releaseDate: Date.parse("2022-07-15"),
        genre: "Extratone",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "i was hurting, but you were there for me (and 300 other reasons i love you)",
        artists: ["Clawrez"],
        album: "2000 OVER!!",
        no: 7,
        releaseDate: Date.parse("2022-07-15"),
        genre: "Extratone",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Death Cheater",
        artists: ["Clawrez"],
        album: "Nikidronov Special Selection",
        no: 1,
        releaseDate: Date.parse("2022-07-28"),
        genre: "Hardcore",
        label: "Nikidronov Labo",
        image: "",
        audioFile: "",
    },
    {
        title: "E-pidemic (Clawrez Remix)",
        artists: ["Flave", "Clawrez"],
        album: "E-pidemic (Clawrez Remix)",
        no: 1,
        releaseDate: Date.parse("2022-09-22"),
        genre: "Frenchcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "ascensionism",
        artists: ["kevlar"],
        album: "ascensionism",
        no: 1,
        releaseDate: Date.parse("2022-09-26"),
        genre: "Splittercore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "burden",
        artists: ["kevlar"],
        album: "burden",
        no: 1,
        releaseDate: Date.parse("2022-10-14"),
        genre: "Experimental",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Fox's First Gabber",
        artists: ["Clawrez"],
        album: "Fox's First Gabber",
        no: 1,
        releaseDate: Date.parse("2022-11-15"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "emotional collision",
        artists: ["Clawrez", "kevlar"],
        album: "emotional collision",
        no: 1,
        releaseDate: Date.parse("2022-11-22"),
        genre: "Industrial Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "ORDER (Clawrez Bootleg)",
        artists: ["Heaven Pierce Her", "Clawrez"],
        album: "ORDER (Clawrez Bootleg)",
        no: 1,
        releaseDate: Date.parse("2023-01-23"),
        genre: "Speedcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "DEFENESTRATORS",
        artists: ["Clawrez", "Axley", "(H)", "SCHIRMER", "HVRDTONIC", "Jax", "Abrasic"],
        album: "DEFENESTRATORS",
        no: 1,
        releaseDate: Date.parse("2023-02-24"),
        genre: "Uptempo Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Fox Boy (Clawrez Remix)",
        artists: ["WHSPRS", "Clawrez"],
        album: "Fox Boy (Clawrez Remix)",
        no: 1,
        releaseDate: Date.parse("2023-02-27"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "WE ARE LOUD (Clawrez Edit)",
        artists: ["EQUAL2", "Clawrez"],
        album: "WE ARE LOUD (Clawrez Edit)",
        no: 1,
        releaseDate: Date.parse("2023-03-02"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Retaliation",
        artists: ["Clawrez"],
        album: "Retaliation",
        no: 1,
        releaseDate: Date.parse("2023-03-14"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Pendulum",
        artists: ["Clawrez", "EQUAL2"],
        album: "Retaliation",
        no: 2,
        releaseDate: Date.parse("2023-03-14"),
        genre: "Xtra Raw",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Mosquito",
        artists: ["Clawrez"],
        album: "Retaliation",
        no: 3,
        releaseDate: Date.parse("2023-03-14"),
        genre: "Terrorcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Milo Simulator",
        artists: ["Clawrez"],
        album: "KILL THE STARS",
        no: 1,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "IMMENSE",
        artists: ["Clawrez"],
        album: "KILL THE STARS",
        no: 2,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Hampton Lane",
        artists: ["Clawrez"],
        album: "KILL THE STARS",
        no: 3,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "1.8288 Metres Under",
        artists: ["Clawrez", "ZiKK"],
        album: "KILL THE STARS",
        no: 4,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Uptempo Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Symphorophilia",
        artists: ["Clawrez"],
        album: "KILL THE STARS",
        no: 5,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Jack Of(f) Clubs",
        artists: ["Clawrez", "kevlar", "ZiKK"],
        album: "KILL THE STARS",
        no: 6,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Harshcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Your screams will not be heard through the concrete walls. (2023 Remix)",
        artists: ["Clawrez"],
        album: "KILL THE STARS",
        no: 7,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Industrial Hardcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "i am hurting (and 400 other things that aren't quite right)",
        artists: ["Clawrez"],
        album: "KILL THE STARS",
        no: 8,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Extratone",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Everything Dies",
        artists: ["Clawrez", "kevlar"],
        album: "KILL THE STARS",
        no: 9,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Doomcore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Duloxetine",
        artists: ["Clawrez"],
        album: "KILL THE STARS",
        no: 10,
        releaseDate: Date.parse("2023-05-11"),
        genre: "Piano",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "red room key gen",
        artists: ["kevlar"],
        album: "red room key gen",
        no: 1,
        releaseDate: Date.parse("2023-05-13"),
        genre: "Breakcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "THiS ZONG MAKEZ ME BOUNZE iN MY CHAiR",
        artists: ["ZiKK"],
        album: "THiS ZONG MAKEZ ME BOUNZE iN MY CHAiR",
        no: 1,
        releaseDate: Date.parse("2023-06-26"),
        genre: "Uptempo Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Control Panel",
        artists: ["Clawrez"],
        album: "Control Panel",
        no: 1,
        releaseDate: Date.parse("2023-07-07"),
        genre: "Splittercore",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "Utopia Overture (Clawrez Bootleg)",
        artists: ["Cristobal Tapia De Veer", "Clawrez"],
        album: "Utopia Overture (Clawrez Bootleg)",
        no: 1,
        releaseDate: Date.parse("2023-07-15"),
        genre: "Uptempo Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Only Kicks (Clawrez Edit)",
        artists: ["Krowdexx", "Clawrez"],
        album: "Only Kicks (Clawrez Edit)",
        no: 1,
        releaseDate: Date.parse("2023-08-18"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "ATTACK",
        artists: ["Clawrez"],
        album: "NEOURANIUM VOL.1",
        no: 12,
        releaseDate: Date.parse("2023-10-07"),
        genre: "Xtra Raw",
        label: "Cokolwiecore",
        image: "",
        audioFile: "",
    },
    {
        title: "RAINBOW STIMULANT",
        artists: ["Clawrez"],
        album: "RAINBOW STIMULANT",
        no: 1,
        releaseDate: Date.parse("2023-10-19"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Do It For (Clawrez Bootleg)",
        artists: ["The Purge", "Clawrez"],
        album: "Do It For (Clawrez Bootleg)",
        no: 1,
        releaseDate: Date.parse("2023-11-11"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "CRUNCHTiME",
        artists: ["Clawrez", "ZiKK"],
        album: "CRUNCHTiME",
        no: 1,
        releaseDate: Date.parse("2024-01-19"),
        genre: "Uptempo Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Hai La Noi (ZiKK'Z 300 KiKKZ PER MiNUTE EDiT)",
        artists: ["NSD", "ZiKK"],
        album: "Hai La Noi (ZiKK'Z 300 KiKKZ PER MiNUTE EDiT)",
        no: 1,
        releaseDate: Date.parse("2024-02-01"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "ETERNAL DAMNATION",
        artists: ["Clawrez"],
        album: "ETERNAL DAMNATION",
        no: 1,
        releaseDate: Date.parse("2024-02-16"),
        genre: "Xtra Raw",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "red room key gen (more lives taken)",
        artists: ["Clawrez", "kevlar"],
        album: "AETHER BREAK VOL​.​1",
        no: 1,
        releaseDate: Date.parse("2024-03-02"),
        genre: "Hardcore",
        label: "Cokolwiecore",
        image: "",
        audioFile: "",
    },
    {
        title: "EAT MY KNiFE",
        artists: ["ZiKK"],
        album: "EAT MY KNiFE",
        no: 1,
        releaseDate: Date.parse("2024-05-28"),
        genre: "Rawtempo",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "DON'T WEEP",
        artists: ["Clawrez"],
        album: "DON'T WEEP",
        no: 1,
        releaseDate: Date.parse("2024-06-06"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "SWITCH THE BASS",
        artists: ["Clawrez"],
        album: "SWITCH THE BASS",
        no: 1,
        releaseDate: Date.parse("2024-06-27"),
        genre: "Xtra Raw",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "DIGIT4L SU1CIDE (Clawrez Edit)",
        artists: ["The Smiler", "Clawrez"],
        album: "DIGIT4L SU1CIDE (Clawrez Edit)",
        no: 1,
        releaseDate: Date.parse("2024-07-06"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
]