const DISCOGRAPHY = [
    {
        title: "Do It For (Clawrez Bootleg)",
        artists: ["The Purge", "Clawrez"],
        album: "Do It For (Clawrez Bootleg)",
        no: 1,
        releaseDate: Date.parse("2023-11-11"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "CRUNCHTiME",
        artists: ["Clawrez", "ZiKK"],
        album: "CRUNCHTiME",
        no: 1,
        releaseDate: Date.parse("2024-01-19"),
        genre: "Uptempo Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Hai La Noi (ZiKK'Z 300 KiKKZ PER MiNUTE EDiT)",
        artists: ["NSD", "ZiKK"],
        album: "Hai La Noi (ZiKK'Z 300 KiKKZ PER MiNUTE EDiT)",
        no: 1,
        releaseDate: Date.parse("2024-02-01"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "ETERNAL DAMNATION",
        artists: ["Clawrez"],
        album: "ETERNAL DAMNATION",
        no: 1,
        releaseDate: Date.parse("2024-02-16"),
        genre: "Xtra Raw",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "red room key gen (more lives taken)",
        artists: ["Clawrez", "kevlar"],
        album: "AETHER BREAK VOL​.​1",
        no: 1,
        releaseDate: Date.parse("2024-03-02"),
        genre: "Hardcore",
        label: "Cokolwiecore",
        image: "",
        audioFile: "",
    },
    {
        title: "EAT MY KNiFE",
        artists: ["ZiKK"],
        album: "EAT MY KNiFE",
        no: 1,
        releaseDate: Date.parse("2024-05-28"),
        genre: "Rawtempo",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "DON'T WEEP",
        artists: ["Clawrez"],
        album: "DON'T WEEP",
        no: 1,
        releaseDate: Date.parse("2024-06-06"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "SWITCH THE BASS",
        artists: ["Clawrez"],
        album: "SWITCH THE BASS",
        no: 1,
        releaseDate: Date.parse("2024-06-27"),
        genre: "Xtra Raw",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "DIGIT4L SU1CIDE (Clawrez Edit)",
        artists: ["The Smiler", "Clawrez"],
        album: "DIGIT4L SU1CIDE (Clawrez Edit)",
        no: 1,
        releaseDate: Date.parse("2024-07-06"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },

    {
        title: "Do It For (Clawrez Bootleg)",
        artists: ["The Purge", "Clawrez"],
        album: "Do It For (Clawrez Bootleg)",
        no: 1,
        releaseDate: Date.parse("2023-11-11"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "CRUNCHTiME",
        artists: ["Clawrez", "ZiKK"],
        album: "CRUNCHTiME",
        no: 1,
        releaseDate: Date.parse("2024-01-19"),
        genre: "Uptempo Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "Hai La Noi (ZiKK'Z 300 KiKKZ PER MiNUTE EDiT)",
        artists: ["NSD", "ZiKK"],
        album: "Hai La Noi (ZiKK'Z 300 KiKKZ PER MiNUTE EDiT)",
        no: 1,
        releaseDate: Date.parse("2024-02-01"),
        genre: "Terrorcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "ETERNAL DAMNATION",
        artists: ["Clawrez"],
        album: "ETERNAL DAMNATION",
        no: 1,
        releaseDate: Date.parse("2024-02-16"),
        genre: "Xtra Raw",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "red room key gen (more lives taken)",
        artists: ["Clawrez", "kevlar"],
        album: "AETHER BREAK VOL​.​1",
        no: 1,
        releaseDate: Date.parse("2024-03-02"),
        genre: "Hardcore",
        label: "Cokolwiecore",
        image: "",
        audioFile: "",
    },
    {
        title: "EAT MY KNiFE",
        artists: ["ZiKK"],
        album: "EAT MY KNiFE",
        no: 1,
        releaseDate: Date.parse("2024-05-28"),
        genre: "Rawtempo",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "DON'T WEEP",
        artists: ["Clawrez"],
        album: "DON'T WEEP",
        no: 1,
        releaseDate: Date.parse("2024-06-06"),
        genre: "Hardcore",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
    {
        title: "SWITCH THE BASS",
        artists: ["Clawrez"],
        album: "SWITCH THE BASS",
        no: 1,
        releaseDate: Date.parse("2024-06-27"),
        genre: "Xtra Raw",
        label: "LUX MARBLE",
        image: "",
        audioFile: "",
    },
    {
        title: "DIGIT4L SU1CIDE (Clawrez Edit)",
        artists: ["The Smiler", "Clawrez"],
        album: "DIGIT4L SU1CIDE (Clawrez Edit)",
        no: 1,
        releaseDate: Date.parse("2024-07-06"),
        genre: "Xtra Raw",
        label: "Self-Released",
        image: "",
        audioFile: "",
    },
]